# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - CalvaryGPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://calvarygtp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f7a2526f975e47e28cc40a26ac91d0fa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1ecbeec6c1564c5fa8d05b3ceefdca60 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: calvarygtp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f7a2526f975e47e28cc40a26ac91d0fa }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CalvaryGPT'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_26f708042c9a4e3b952245a83be9eb63 }}
        images: 'calvarygtp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f7a2526f975e47e28cc40a26ac91d0fa }}/sample-app-aoai-chatgpt:${{ github.sha }}'