# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 57cdcad2-7230-59a3-b47b-9631ebe53a7e

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://calvarygtp2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ad003395fd4a49a28dd9f17f250aa256 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b17893e1770f4a689ea4a39f4833acfd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: calvarygtp2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad003395fd4a49a28dd9f17f250aa256 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '57cdcad2-7230-59a3-b47b-9631ebe53a7e'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a8fb11909f1a40278b6b4a08495e1c0d }}
        images: 'calvarygtp2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ad003395fd4a49a28dd9f17f250aa256 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}'